config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  get '/balances/report', to: 'balances#show'
  get '/balances', to: 'balances#new'
  
  resources :balances
end

app/models/acumulated.rb
class Acumulated < ApplicationRecord
  belongs_to :report
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :description, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name,:phone,:location,:fixed_salary, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name,:phone,:location,:fixed_salary,:email, :password, :current_password)}
         end

end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
    def new
        @balance = Balance.new
    end

    def create
        @balance = Balance.new(balance_params)
        @balance.user_id = 1
        # @balance.date = Time.now.strftime("%Y","%m","%d") 
        if @balance.save
            redirect_to new_balance_path
        else
            render :new , status: :unprocessable_entity
        end
    end
    
    def show
        balance = Balance.all
    end

    private
    def balance_params
      params.require(:balance).permit(:description, :entry_type, :quantity, :category_id,:currency_cents, :date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_base.html.erb
<div class="header">
  <h3 class="subtitle is-3 has-text-white">Welcome <%= current_user.name %></h3>
  <p>Resize the browser window to see the responsive effect.</p>
</div>

<div class="topnav">
  <a href="/balances">Balance</a>
  <a href="/balances/report">Balance Report</a>
  <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
</div>

<style>
* {
  box-sizing: border-box;
}

/* Style the header */
.header {
  background-color: #23292D;
  padding: 20px;
  text-align: center;
  color:#5073B8;
}

/* Create three equal columns that floats next to each other */
.topnav {
  overflow: hidden;
  background-color: #333;
}
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media screen and (max-width:600px) {
  .column {
    width: 100%;
  }
}
</style>

app/views/application/_form.html.erb
<%= form_with model: @balance do |form|%>
   <p class="title is-2">Balance</p>
    <div >
      <div class="columns">
        <div class="column is-one-fifth">
          <label class="label">Entry type</label>
            <div class="select is-medium">
              <%= form.select :entry_type, ['income', 'expend'], selected: 'Entry type'%>
            </div>
        </div>

        <div class="column is-one-fifth">
          <label class="label">Reason of the entry</label>
            <div class="select is-medium">
              <%= form.select :category_id, [['cash',4],['receivables',4],['stock',4]], selected: 'Entry type'%>
            </div>
        </div>

        <div class="column is-one-quarter">
          <label class="label">Quantity</label>
          <p class="control has-icons-left">
            <%= form.text_field :quantity , class: "input is-medium" %>
            <span class="icon is-small is-left">
              <i class="fas fa-dollar-sign"></i>
            </span>
          </p>
        </div>

        <div class="column is-one-quarter">
          <label class="label">Date</label>
          <p class="control has-icons-left">
            <%= form.text_field :date , class: "input is-medium", placeholder: "yyyy-mm-dd" %>
            <span class="icon is-small is-left">
              <i class="fas fa-calendar-day"></i>
            </span>
          </p>
        </div>

      </div>
      <div class="columns">
        <div class="column is-three-quarters">
          <label class="label">Description</label>
          <%= form.text_area :description , class: "textarea is-hovered", placeholder: "Description of your entry"%>
        </div>
      </div>

      <div >
          <%= form.submit class:"button is-link is-outlined"%>
      </div>
  </div>
<% end %>

app/views/application/_landing.html.erb
<section class="hero is-info is-large">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-start">
          <a class="navbar-item">
            <span class="icon" style="font-size: 45px; ">
              S
              <i class="fas fa-mountain"></i>
              VE
            </span>
          </a>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <a class="button is-info is-inverted">
                <span class="icon" style="font-size: 30px;" >
                  <i class="fas fa-user-astronaut"></i>
                </span>
                <a class="navbar-item" href="/users/sign_in">Login </a>
              </a>
            </span>
            <span class="navbar-item">
              <a class="button is-info is-inverted">
                <span class="icon" style="font-size: 30px; ">
                  <i class="fas fa-user-astronaut"></i>
                </span>
                <a class="navbar-item" href="/users/sign_up" >Sing up</a>
              </a>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        Take control of your money now
      </p>
      <p class="subtitle">
        <span  style="font-size: 47px;" >
          <i class="fas fa-file-invoice-dollar"></i>
          <i class="fas fa-wallet"></i>
          <i class="fas fa-money-bill-wave"></i>
          <i class="far fa-bell"></i>
        </span>
      </p>
      
    </div>
  </div>

  <div class="hero-foot">
    <nav class="tabs is-boxed is-fullwidth">
      
    </nav>
  </div>
</section>
<section class="hero is-link">
  <div class="hero-body">
    <p class="subtitle">
      The perfect soluction to keep accounts of your account
    </p>
  </div>
</section>

app/views/application/_menu.html.erb
<div class="vertical-menu">
  <a href="/" class="active">
    <span class="icon" style="font-size: 20px; ">
    <i class="fas fa-igloo"></i>
    </span>
    HOME
  </a>
  <a href="/balances">Balance</a>
  <a href="/balances/report">Balance Report</a>
  <a href="#">Link 3</a>
  <a href="#">Link 4</a>
 <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete, class:"button is-link is-light"%>
</div>

<style>
.vertical-menu {
  width: auto;
}

.vertical-menu a {
  background-color: #FDFDFD;
  color: black;
  display: block;
  padding: 12px;
  text-decoration: none;
  height: 55px;
}

.vertical-menu a:hover {
  background-color: #5073B8;
}

.vertical-menu a.active {
  background-color: #5073B8;
  color: white;
}
</style>

app/views/application/_notification.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/balances/new.html.erb
<% if current_user %>
  <%= render "base" %>
  
  <div class="container is-max-desktop pt-5">
    <%= render "form" %>
  </div>
<% end %>

app/views/balances/show.html.erb
<% if current_user %>
    <%= render "base" %>
    <div class="container is-max-desktop pt-5">
        <div class="columns">
            <div class="column">
                <p class="title is-2">Balance</p>
            </div>
            <div class="column">
                
            </div>
            <div class="column">
            
            </div>
            <div class="column">
                <%= link_to "New balance", balances_path ,class:'button is-link is-outlined' %>
            </div>
        </div>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ledger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">
    <script src="https://kit.fontawesome.com/bb8d52425c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
<%= render "base" %>
<% else %>
<%= render "landing" %>
<% end %>